### ISSUE TITLE
Error with CreateRenderTarget at Quadifier.cpp line 1235 when antialiasing is enabled

### ISSUE THREAD

**Issue by LinghanLiu** [jam3sward/quadifier#14]
Error Log: ‘error: failed to create DX render target;’
Decription: Unity use antialiasing, So MultiSample  != D3DMULTISAMPLE_NONE
My solution：
Quadifier.cpp 1225 line
if (m_device->CreateRenderTarget(
			m_width,
			m_height,
			displayMode.Format,
			desc.MultiSampleType,
			desc.MultiSampleQuality,
			FALSE,
			&m_target[i].surface,
			NULL//&m_target[i].shareHandle
			) != S_OK) {
			Log::print("error: failed to create DX render target\n");
			exit(1);
			break;
		}
		else
		{
			Log::print("create DX render target success ") << m_target[i].surface << endl;
		}

**Comment by LinghanLiu** [comment]
Some camera image effect scripts use Antialiasing RenderTexture. The error is same to this issue.

**Comment by JackLikePython** [comment]
Thanks for your help. I have created issues for (2) and (3)  : )

**Comment by jam3sward** [comment]
I believe this is a duplicate of issue #12 which was fixed and closed at https://github.com/jam3sward/quadifier/commit/d8bcabdd31fb8fbea1ed5e66f2ce4c38e839379f

The fix is essentially the same as what you have proposed above, except that my fix passes NULL for NVIDIA, and passes a share handle for AMD.

The first version of Quadifier used to pass NULL there, but it was later change to a share handle for AMD/ATI compatibility at https://github.com/jam3sward/quadifier/commit/8e31d821e69158f8d45f4b4d65262147f44cd7e9. At the time, this worked on both NVIDIA and AMD/ATI. However, it seems that this breaks anti-aliasing support on more recent NVIDIA driver versions, so the current revision includes a fix for this, as described above and on #12.
