### ISSUE TITLE
Unity Scripts

### ISSUE THREAD

**Issue by AWEvSOdME** [jam3sward/quadifier#4]
Hi James, 

first thank you a lot for sharing your work. I have a simple question. In the wiki it's mentioned that there are scripts necessary to render left and right channels in the correct order ("It requires some scripts on the Unity side to render the left and right channels in the correct order"). But for me when i build a Unity scene with two cameras (left, right) without any scripts and start it via Quadifier everything looks pretty good. Do I get something totally wrong or do I miss something?

Thank you
Paul

**Comment by jam3sward** [comment]
Hi Paul

You're very welcome, I'm  pleased you found it useful. Yes, you could certainly create your own cameras in Unity and set up your own stereo viewing system with Quadifier, without using the scripts provided. For a single monitor, you would just create two cameras, one for left eye, one for right eye, covering the full viewport, and render them both in turn. There is a unity setting (camera depth if I remember rightly) which controls which order they are rendered in. Quadifier will assume the first one rendered is the left eye, and the second one is the right eye.
Quadifier captures events like DirectX Clear and Present to capture the view rendered for each camera. There will only be one Present for each frame, but multiple Clear calls, and Quadifier uses this to work out when to capture the view. When it sees two or more Clear calls between each Present, it enables stereo 3D output.
The scripts create multiple cameras, with an appropriate viewing frustum (asymmetric frustum) for correct stereo rendering, and makes sure those cameras are rendered in the right order for Quadifier.
As you have discovered, you can do without the scripts and create the cameras yourself. With two cameras rendered in sequence, you can display any image you like to the left and right eye. However, one reason you might want to use the scripts is that they provide full control over the viewing system (so a technically correct "asymmetric frustum" can be used, rather than using "toe in" stereo for example).
Hope this answers your question?

Kind regards
James

**Comment by AWEvSOdME** [comment]
Hi James, 
wow that was a very detailed answer! Thank you, this answers my question perfectly. :) 

Regards
Paul
