### ISSUE TITLE
Four problems

### ISSUE THREAD

**Issue by LinghanLiu** [jam3sward/quadifier#9]
Hi James,
There are four problems bothering me.
1.Can't attach camera image effect scripts.(Error:Error Setting Render Target at beginCapture() SetRenderTarget(......));
2.Left/Right eye is not always in Left/Right sequence, Sometimes in Right/Left sequence;
3.When I drag the window with the mouse. Mouse event and Keyboard event will be invalid(Unity scripts);
4.CreateRenderTarget : MultiSample != D3DMULTISAMPLE_NONE => error: failed to create DX render target;
Any suggestion for me? :）

**Comment by JackLikePython** [comment]
In Addition,
4.CreateRenderTarget : MultiSample != D3DMULTISAMPLE_NONE => error: failed to create DX render target

**Comment by LinghanLiu** [comment]
1 and 4 I have worked it out. 3 is too hard for me to solve.

**Comment by LinghanLiu** [comment]
Windows message 1025 conflict with m_frameDone.wait(1000);

**Comment by LinghanLiu** [comment]
if (m_frameDone.wait(1000))
		flag = false;

case WM_USER_NEWFRAME:
		if (!flag)
		{
			redraw();
			return 0L;
		}
		else
		{
			return DefWindowProc(hWnd, uMsg, wParam, lParam);
		}

**Comment by jam3sward** [comment]
Excuse the lack of response on this, I could use some more information to be able to help with these. Ideally I would like to close this issue, and ticket the individual issues, rather than report 4 on 1.

Anyway, here is some initial feedback on the four items above:
1. If these are post-processing image effects, they are not expected to work with Quadifier. If you can give more detail on steps (or example scene) to reproduce, I may be able to comment further. You mention that you have worked out (1), please can you expand on this?
2. I can't reproduce this, but if you can give some further detail or steps to reproduce we can create a separate issue for this specific problem.
3. Again, if you can give some more information we can create a separate issue for this and investigate.
4. From the description, I think this one is issue #12 and it is fixed now.

You've also posted some code above (thanks) but I'm not sure which issue it relates to? If you can provide a bit more detail, I can create issues for (2) and (3) above and then I'll close this issue #9.

**Comment by LinghanLiu** [comment]
Thanks for your help. I have created issues for (2) and (3) : )

**Comment by jam3sward** [comment]
Thanks, for future reference then:
1. Due to issue #12 (fixed) and there's a duplicate issue #14 (closed)
2. New issue #16 created
3. This is issue #15
4. This is issue #12 (fixed) same as (1) above.
Now closing this ticket.
